### ISSUE TITLE
1. Installing Conda on Mac

### ISSUE THREAD

**Issue by kanusek** [feldroy/django-crash-course#103]
* Chapter or Appendix: 1. The Ultimate Django setup
* Section: Conda
* Subsection: Installing Conda on Mac

For me and another reader, Conda was not installed into users home directory as suggested.
(I’m on Mojave and he’s on Catalina)

Instead Conda was installed to:
```
/opt/miniconda3/bin/conda
```

**Comment by johnpilbeam** [comment]
The GUI pkg installer failed silently (on both Catalina and Mojave). The installer runs, but then the conda command is not available even after running the Troubleshooting commands and closing/opening a new terminal. I used the [BASH installer](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh) instead: 
Installed to:
`/Users/username/miniconda3`
After install I got the following error in the terminal and in VS Code:
`NotWritableError: The current user does not have write permissions to a required path.`
Fixed with:
`sudo chown -R username /Users/username/miniconda3 && sudo chown -R username /Users/username/.conda`
It worked, but I don't know if this is a good solution to the issue.

**Comment by pydanny** [comment]
Later this week we're going to spend a whole day on the Ultimate Django Setup.

**Comment by pydanny** [comment]
I believe this has been resolved. If I am incorrect, please reopen.

**Comment by pydanny** [comment]
🚢 🧀
