### ISSUE TITLE
Explain migrations

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#191]
## Description 

Migration files are never actually explained

## Possible Solutions

It should be explained what migrations are.  
You may also want to explain `sqlmigrate`, `showmigrations`, how to revert a migration, how to create an empty migration...

**Comment by quique** [comment]
In #220  Laurent Steffan proposes adding a few lines, that I think would be helpful.

**Comment by pydanny** [comment]
@luzfcb said in private slack:

> we can quickly explain when Django require to create a new migration. ( Whenever there is a change in the models, in the fields of the models, in the attributes of the fields of the models, and in the internal meta class.)

**Comment by quique** [comment]
Yep. I think Laurent's proposed text could be used nearly verbatim.

**Comment by luzfcb** [comment]
Since django migrations can be generated from actions that do not affect or touch the database, we must take care to not couple the database to the migration explanation.

Eg.: if we change the `help_text` from a field of a model, that action will generate a new migration but will not touch the database.

**Comment by pydanny** [comment]
Using @lmsteffan's excellent explanation from #220
