### ISSUE TITLE
29.1: everycheese/cheeses pytest issue

### ISSUE THREAD

**Issue by leigh-data** [feldroy/django-crash-course#223]
## Pytest run issues

When the last commited code runs
`coverage -m pytest`

the followings issue pops up:

```
raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'cheeses'. Check that 'everycheese.cheeses.apps.CheesesConfig.name' is correct.
```

`
LOCAL_APPS = [
    "everycheese.users.apps.UsersConfig",
    'everycheese.cheeses.apps.CheesesConfig',
]
`

## Possible Solutions
When the LOCAL_APPS list is this
`
LOCAL_APPS = [
    "everycheese.users.apps.UsersConfig",
    'everycheese.cheeses',
]
`
pytest runs with no issues

The diff is here: [github](https://github.com/leigh-data/everycheese/commit/6444901af918546697ef5eb000cf4a6423c575af)

**Comment by luzfcb** [comment]
@leigh-data Thanks to open an issue. 
I tried to look at your repository, but I got and 404 error. I suppose that your repository is a private repository.

**Comment by leigh-data** [comment]
It was private. It is now public.

**Comment by leonlan** [comment]
Having the same problem. My solution is to change the code in cheeses/apps.py to 

> from django.apps import AppConfig
> class CheesesConfig(AppConfig):
>     name = 'everycheese.cheeses'

**Comment by pydanny** [comment]
@leonlan's answer above is correct. This is how apps.py is to be configured. The code that will work matches his and is in the book:

``` python
from django.apps import AppConfig


class CheesesConfig(AppConfig):
    name = 'everycheese.cheeses'
```

**Comment by firepol** [comment]
That's funny, I copied/pasted exactly the code from the book `name = 'everycheese.cheeses'` in the appy.py file and I got this same error:

`django.core.exceptions.ImproperlyConfigured: Cannot import 'cheeses'. Check that 'everycheese.cheeses.apps.CheesesConfig.name' is correct.`

Then I searched this repo, found this issue, checked what typo leonlan did in his apps.py file. So I changed (my code, that I pasted from the book) to name = 'cheeses', I did run `coverage run -m pytest` and I got the same error:

`django.core.exceptions.ImproperlyConfigured: Cannot import 'cheeses'. Check that 'everycheese.cheeses.apps.CheesesConfig.name' is correct.`

Then I undid the change, so that it reverted to what gave me an error before: `name = 'everycheese.cheeses'`

I run `coverage run -m pytest` and now it works, strange... Basically if you get this error you can change the name and put whatever you want, try to run the code, make it fail, then put the proper name...
