### ISSUE TITLE
Default value is missing user/password/host information

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#320]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-11
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 18
* Section: 4

## Description 
Section 18.4 contains a snippet from `base.py` saying it should contain `postgres://user:passwd@localhost:5432/everycheese`, but here I get `postgres:///everycheese` which actually seems to be correct when I look at the GitHub source code of `django-crash-starter`, as it contains the template `"postgres:///{{cookiecutter.project_slug}}"` which is consistent with the user/password/host information missing...

## Possible Solutions
I don't know if this is something to fix in the book or in the `django-crash-starter` project?

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by luzfcb** [comment]
@grondman Thanks to open a issue.

This is something that will be fixed in the next update of the book.

Please follow the steps below to get it resolved.

Please let me know if you have any more trouble.

1 - Install the dependencies inside the `everycheese` conda environment ( `conda activate everycheese` ):
The command below must be executed inside the project folder.

```bash
pip install -r requirements/local.txt
```

2 - Ensure that in your "everycheese/config/settings/base.py" contains this [[1]](https://gist.github.com/luzfcb/a80c6a54bf04df7a41811b045903bfb4) content before the `# GENERAL`

[1] https://gist.github.com/luzfcb/a80c6a54bf04df7a41811b045903bfb4

(the latest version of django-crash-starter already includes the content of the previous file.)

3 - On the root directory of your everycheese project, create a file named `.env` (that is, the `.env` file must be in the same directory as the `manage.py` file)

```bash
touch .env
```

4 - add the following configuration to the `.env` file and save the changes.

```bash
DATABASE_URL=postgres://myuser:mypasswd@localhost:5432/everycheese
```

5 - Edit the `.gitignore` file and add `.env` and save the changes.

6 - Run `python manage.py sqlcreate`

You should get this output:

```sql
CREATE USER myuser WITH ENCRYPTED PASSWORD 'mypasswd' CREATEDB;
CREATE DATABASE everycheese WITH ENCODING 'UTF-8' OWNER "myuser";
GRANT ALL PRIVILEGES ON DATABASE everycheese TO myuser;
```

<a name="step-7"></a>
7 - Execute the command below to create the database user with the given password, create the database and link the user to the newly created database.

On Linux:

```bash
python manage.py sqlcreate | sudo -u postgres psql -U postgres
```

On Mac:

```
python manage.py sqlcreate | psql
```

## Troubleshooting

If for some reason you get an error similar to this:

```sql
ERROR:  syntax error at or near "WITH"
LINE 1: CREATE USER  WITH ENCRYPTED PASSWORD '' CREATEDB;
                     ^
ERROR:  zero-length delimited identifier at or near """"
LINE 1: CREATE DATABASE everycheese WITH ENCODING 'UTF-8' OWNER "";
                                                             ^
ERROR:  syntax error at or near ";"
LINE 1: GRANT ALL PRIVILEGES ON DATABASE everycheese TO ;
```

Or

```sql
ERROR:  role "myuser" already exists
ERROR:  database "everycheese" already exists
GRANT
```

You can delete the database and the user with the commands below and then [perform step 7 again](#step-7).

> :warning: **Be very careful here!**: The commands below erase data, and should only be executed on your local development machine and **NEVER** on a production server.


On Linux:

```bash
sudo -u postgres dropdb -U postgres --if-exists everycheese
sudo -u postgres dropuser -U postgres --if-exists myuser
```

On Mac:

```bash
dropdb --if-exists everycheese
dropuser --if-exists myuser
```

**Comment by bummmer** [comment]
This worked, thank you.
